first try TDD
piedra-de-flor/Lotto pull request #1
Opened 2023-09-22 16:48 UTC by piedra-de-flor

2023-09-27 06:45 UTC, kakao-gray-great requested changes
코드 짜시느라 고생하셨습니다~~

간단한 리뷰들 남겨놨으니 확인해주세요!
추가 의견은 멘토링 시간에 확인해보면 좋을 것 같습니다.

2023-09-27 06:45 UTC, kakao-gray-great commented on src/main/java/LottoGame/Lotto/controller/Game.java
> +        money = new Money(InputView.getInstance().inputMoney(), LOTTO_PRICE);
현재 Game에서 money라는 상태를 가지고 있는데, 이런 구조면 어떠한 문제가 생길 수 있을까요?

2023-09-27 06:45 UTC, kakao-gray-great commented on src/main/java/LottoGame/Lotto/model/LottoManager.java
> +public class LottoManager {
Manager라는 네이밍을 많이 사용하시는데 어떤 의미로 사용을 하시는건가요?

2023-09-27 06:45 UTC, kakao-gray-great commented on src/main/java/LottoGame/Lotto/view/OutputView.java
> +        System.out.println(WinningsCount.FIRST_PLACE.correctCount + "개 일치 (" + WinningPrice.FIRST_PRICE.price + "원)- " + result.get(WinningsCount.FIRST_PLACE.correctCount) + "개");
이렇게 다 직접 찍어줘야할까요?

2023-09-27 06:45 UTC, kakao-gray-great commented on src/main/java/LottoGame/Lotto/vo/Money.java
> +    private final int money;
객체와 상태가 네이밍이 중복해서 가독성이 좋지 않은 것 같아요.

2023-09-27 12:19 UTC, piedra-de-flor commented on src/main/java/LottoGame/Lotto/model/LottoManager.java
> +public class LottoManager {
특정 객체를 생성하고 보관하는 역할의 특정 객체 관리자로 Manager라는 네이밍을 사용하였습니다.
단순히 생성만 해주는 역할이었다면 Maker라는 네이밍을 하였겠지만 추가적인 기능이 있기에 Manager로 하였습니다

2023-09-27 16:23 UTC, piedra-de-flor commented on src/main/java/LottoGame/Lotto/view/OutputView.java
> +        System.out.println(WinningsCount.FIRST_PLACE.correctCount + "개 일치 (" + WinningPrice.FIRST_PRICE.price + "원)- " + result.get(WinningsCount.FIRST_PLACE.correctCount) + "개");
반복문으로 처리하도록 리팩터링 했습니다!

2023-09-30 08:43 UTC, piedra-de-flor commented on src/main/java/LottoGame/Lotto/controller/Game.java
> +        money = new Money(InputView.getInstance().inputMoney(), LOTTO_PRICE);
이건 정말 모르겠습니다...

2023-09-30 08:43 UTC, piedra-de-flor commented on src/main/java/LottoGame/Lotto/controller/Game.java
> +        money = new Money(InputView.getInstance().inputMoney(), LOTTO_PRICE);
money가 바뀌면 Game도 함께 바뀌어야 한다는 것 밖에 생각이 나질 않네요..

2023-10-08 07:51 UTC, merged